spring:
  application:
    name: payment-service
server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*" # Shows all Actuator endpoints
  endpoint:
    health:
      show-details: always # Shows details of health status

order:
  service:
    url: http://localhost:8082/api/orders